import type { Metadata } from "next";
import { Roboto, Barlow_Condensed } from "next/font/google";
import WrapperThemeProvider from "./WrapperThemeProvider";
import { GlobalStyle } from "@/styles/globalStyle";
import Header from "@/components/Header";

const roboto = Roboto({
  variable: "--font-default",
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["100", "300", "600", "900"],
});

const barlowCondensed = Barlow_Condensed({
  variable: "--font-title",
  subsets: ["latin"],
  weight: ["100", "300", "600", "900"],
  style: ["italic", "normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.variable} ${barlowCondensed.variable}`}>
        <WrapperThemeProvider>
          <GlobalStyle />
          <Header />
          {children}
        </WrapperThemeProvider>
      </body>
    </html>
  );
}
